import * as fs from "fs";
import * as path from "path";
import { AST, Statement, Expression } from "../parser";
import { log } from "../utils/logger";

export function compileToNode(ast: AST, outDir: string, name: string) {
  log.info(`Generating Node.js (ESM) for ${name}...`);
  if (ast.functions.length === 0) return;

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  let code = `/**\n * Generated by Bridge from ${name}.bridge\n * Target: Node.js (Bare JavaScript)\n */\n\n`;

  for (const fn of ast.functions) {
    // 1. Map Parameters (Names only, no types)
    const params = fn.params.map((p) => p.name).join(", ");

    code += `export function ${fn.name}(${params}) {\n`;

    // 2. Process Statements
    for (const stmt of fn.body) {
      code += `    ${compileStatement(stmt)}\n`;
    }

    code += `}\n\n`;
  }

  const outFile = path.join(outDir, `${name}.js`);
  fs.writeFileSync(outFile, code.trim() + "\n");
  log.success(`Generated: ${outFile}`);
}

/**
 * Translates AST Statements to JavaScript code
 */
function compileStatement(stmt: Statement): string {
  switch (stmt.type) {
    case "ReturnStatement":
      return `return ${compileExpression(stmt.expression!)};`;

    case "VariableDeclaration":
      return `let ${stmt.name} = ${compileExpression(stmt.init!)};`;

    case "ExpressionStatement":
      return `${compileExpression(stmt.expression!)};`;

    default:
      return "";
  }
}

/**
 * Translates AST Expressions to JavaScript code
 */
function compileExpression(expr: Expression): string {
  switch (expr.type) {
    case "Literal":
      return expr.value;

    case "Identifier":
      return expr.name!;

    case "BinaryExpression":
      const left = compileExpression(expr.left!);
      const right = compileExpression(expr.right!);
      // JS handles string concatenation and math both with the '+' operator
      return `${left} ${expr.operator} ${right}`;

    case "CallExpression":
      const args = expr.args?.map((arg) => compileExpression(arg)).join(", ");
      return `${expr.name}(${args})`;

    default:
      return "";
  }
}
