import * as fs from "fs";
import * as path from "path";
import { AST, Statement, Expression } from "../parser";
import { log } from "../utils/logger";

export function compileToPHP(ast: AST, outDir: string, name: string) {
  log.info(`Generating Laravel Class for ${name}...`);
  if (ast.functions.length === 0) return;

  const className = name.charAt(0).toUpperCase() + name.slice(1);
  let code = `<?php\n\nnamespace App\\Bridge;\n\n/**\n * Generated by Bridge\n */\nclass ${className}\n{\n`;

  for (const fn of ast.functions) {
    // 1. Parameter Translation
    const params = fn.params
      .map((p) => {
        const type = mapPhpType(p.type);
        return `${type ? type + " " : ""}$${p.name}`;
      })
      .join(", ");

    // 2. Return Type Translation
    const returnType = mapPhpType(fn.returnType);
    const returnHint = returnType ? `: ${returnType}` : "";

    code += `    public function ${fn.name}(${params})${returnHint}\n    {\n`;

    // 3. Statement Translation
    for (const stmt of fn.body) {
      code += `        ${compileStatement(stmt)}\n`;
    }

    code += `    }\n\n`;
  }

  code += `}\n`;

  const outFile = path.join(outDir, `${className}.php`);
  fs.writeFileSync(outFile, code);
  log.success(`Generated: ${outFile}`);
}

/**
 * Translates AST Statements to PHP code
 */
function compileStatement(stmt: Statement): string {
  switch (stmt.type) {
    case "ReturnStatement":
      return `return ${compileExpression(stmt.expression!)};`;

    case "VariableDeclaration":
      return `$${stmt.name} = ${compileExpression(stmt.init!)};`;

    case "ExpressionStatement":
      return `${compileExpression(stmt.expression!)};`;

    default:
      return "";
  }
}

/**
 * Translates AST Expressions to PHP code (Recursive)
 */
function compileExpression(expr: Expression): string {
  switch (expr.type) {
    case "Literal":
      // Literals (strings/numbers) are already formatted by the parser
      return expr.value;

    case "Identifier":
      // Variables get the $ prefix
      return `$${expr.name}`;

    case "BinaryExpression":
      const left = compileExpression(expr.left!);
      const right = compileExpression(expr.right!);

      // Smart Concatenation: PHP uses '.' for strings, '+' for math
      // We assume if '+' is used in Bridge, it maps to '.' for string types
      // or '+' for numeric. For simplicity, we handle the '+' -> '.' swap here
      // if it looks like a string concat, or keep it as '+' for arithmetic.
      let op = expr.operator;
      if (op === "+") {
        // In a "Full" compiler, we'd check types here.
        // Defaulting to '.' for Bridge string compatibility.
        op = ".";
      }
      return `${left} ${op} ${right}`;

    case "CallExpression":
      const args = expr.args?.map((arg) => compileExpression(arg)).join(", ");
      return `$this->${expr.name}(${args})`;

    default:
      return "";
  }
}

/**
 * Maps Bridge types to PHP native types
 */
function mapPhpType(type: string): string {
  const types: Record<string, string> = {
    int: "int",
    string: "string",
    bool: "bool",
    float: "float",
    void: "void",
  };
  return types[type] || "";
}
