import * as fs from "fs";
import * as path from "path";
import { AST, Statement, Expression } from "../parser";
import { log } from "../utils/logger";

export function compileToTypeScript(ast: AST, outDir: string, name: string) {
  log.info(`Generating TypeScript for ${name}...`);
  if (ast.functions.length === 0) return;

  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  let code = `/**\n * Generated by Bridge from ${name}.bridge\n */\n\n`;

  for (const fn of ast.functions) {
    // 1. Map Parameters
    const params = fn.params
      .map((p) => `${p.name}: ${mapTsType(p.type)}`)
      .join(", ");

    // 2. Map Return Type
    const retType = mapTsType(fn.returnType);

    code += `export function ${fn.name}(${params}): ${retType} {\n`;

    // 3. Process Statements
    for (const stmt of fn.body) {
      code += `    ${compileStatement(stmt)}\n`;
    }

    code += `}\n\n`;
  }

  const outFile = path.join(outDir, `${name}.ts`);
  fs.writeFileSync(outFile, code.trim() + "\n");
  log.success(`Generated: ${outFile}`);
}

/**
 * Translates AST Statements to TypeScript code
 */
function compileStatement(stmt: Statement): string {
  switch (stmt.type) {
    case "ReturnStatement":
      return `return ${compileExpression(stmt.expression!)};`;

    case "VariableDeclaration":
      // Bridge 'let' maps directly to TS 'let'
      return `let ${stmt.name} = ${compileExpression(stmt.init!)};`;

    case "ExpressionStatement":
      return `${compileExpression(stmt.expression!)};`;

    default:
      return "";
  }
}

/**
 * Translates AST Expressions to TypeScript code
 */
function compileExpression(expr: Expression): string {
  switch (expr.type) {
    case "Literal":
      return expr.value;

    case "Identifier":
      return expr.name!;

    case "BinaryExpression":
      const left = compileExpression(expr.left!);
      const right = compileExpression(expr.right!);
      // TS uses '+' for both math and string concat, so we keep the operator as is
      return `${left} ${expr.operator} ${right}`;

    case "CallExpression":
      const args = expr.args?.map((arg) => compileExpression(arg)).join(", ");
      return `${expr.name}(${args})`;

    default:
      return "";
  }
}

/**
 * Maps Bridge types to TypeScript native types
 */
function mapTsType(type: string): string {
  const types: Record<string, string> = {
    int: "number",
    float: "number",
    string: "string",
    bool: "boolean",
    void: "void",
  };
  return types[type] || "any";
}
